#!/usr/bin/env node
/**
 * Build-time version information generator
 * 
 * Generates src/version.ts with embedded version and git commit SHA.
 * This ensures version info is available in Docker containers where git isn't present.
 */

import { execSync } from 'child_process'
import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

function getVersionInfo() {
  // Read version from package.json
  const packageJsonPath = join(__dirname, '../package.json')
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'))
  const version = packageJson.version || '0.0.0'

  // Get git commit SHA
  let commitSha = 'unknown'
  try {
    // Try to get from environment variable (Docker build args)
    if (process.env.GIT_COMMIT_SHA) {
      commitSha = process.env.GIT_COMMIT_SHA
    } else {
      // Fallback to git command
      commitSha = execSync('git rev-parse --short HEAD', {
        cwd: join(__dirname, '../..'),
        encoding: 'utf8',
      }).trim()
    }
  } catch (e) {
    console.warn('Warning: Could not determine git commit SHA')
  }

  return { version, commitSha }
}

function generateVersionFile() {
  const { version, commitSha } = getVersionInfo()

  const content = `// Auto-generated by scripts/generate-version.ts
// Do not edit manually - changes will be overwritten on build

export const VERSION = '${version}'
export const COMMIT_SHA = '${commitSha}'
export const BUILD_DATE = '${new Date().toISOString()}'
`

  const outputPath = join(__dirname, '../src/version.ts')
  writeFileSync(outputPath, content)
  console.log(`Generated version.ts: version=${version}, commit=${commitSha}`)
}

generateVersionFile()
